import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: '#FFFFFF',
    },
    logo: {
        width: 66,
        height: 72,
        marginTop: 70,
        borderRadius: 18,
        backgroundColor: '#25CE09',
        alignItems: 'center',
        justifyContent: 'center',
    },
    titleLogo: {
        fontSize: 42,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    title: {
        fontSize: 16,
        marginTop: 16,
        fontWeight: 'bold',
    },
    subtitle: {
        fontSize: 12,
        marginTop: 16,
        color: '#828282',
        fontWeight: 'normal',
    },
    content: {
        width: '100%',
        padding: 10,
        borderWidth: 2,
        borderColor: '#7CB1FF',
        marginTop: 30,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    contentPassword: {
        padding: 10,
        paddingLeft: 10,
        borderWidth: 2,
        borderColor: '#7CB1FF',
        marginTop: 15,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    textInput: {
        flex: 1,
        height: 35,
        marginLeft: 5,
        color: '#828282',
        fontSize: 14,
    },
    button: {
        height: 50,
        width: '100%',
        marginTop: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#1FA309',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 18,
    },
    buttonSocial: {
        height: 50,
        width: '100%',
        marginTop: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderRadius: 10,
    },
    imageGoogle: {
        marginRight: 10,
    },
    buttonSocialText: {
        color: '#000',
        fontSize: 18,
    },
    forgotPassword: {
        height: 30,
        marginTop: 10,
        width: '100%',
        marginRight: 5,
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    forgotPassworText: {
        color: '#828282',
    },
    textLink: {
        fontSize: 15,
        color: '#1FA309',
        fontWeight: 'bold',
    },
    forgotRegister: {
        height: 30,
        marginTop: 30,
        width: '100%',
        marginRight: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    forgotRegisterText: {
        color: '#828282',
    },
});
